# Generated by Django 4.0.2 on 2022-02-22 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=256)),
                ('slug', models.SlugField(max_length=256)),
                ('icon', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('price', models.IntegerField()),
                ('price_type', models.CharField(choices=[('$', 'USD'), ('UZS', 'UZS'), ('₽', 'RUB')], max_length=5)),
                ('color', models.CharField(choices=[('qizil', 'qizil'), ('sariq', 'sariq'), ('qora', 'qora')], max_length=50)),
                ('size', models.JSONField(default={'height': 0, 'len': 0, 'width': 0})),
                ('short_description', models.TextField()),
                ('ctg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitee.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitee.product')),
            ],
        ),
    ]
