# Generated by Django 4.0.2 on 2022-02-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
